{{- if .Values.ingress.tls }}
{{- range .Values.ingress.tls }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .secretName }}-le
  namespace: boiarnikov-a-hw7
spec:
  secretName: {{ .secretName }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: {{ index .hosts 0 }} 
  dnsNames:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
{{- end }}
{{- end }}
