apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-httpd
  namespace: boiarnikov-a-hw7
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-httpd
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-httpd
    spec:
      containers:
        - name: httpd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
