---
- name: Start NGINX
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: started

- name: Reload NGINX
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded

- name: Restart NGINX
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: restarted

