---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: boiarnikov-a-hw3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: httpd-conf 
              key: APP_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
