---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: boiarnikov-a-hw3 
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
