---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-master-rb
  namespace: boiarnikov-a-hw5
subjects:
- kind: ServiceAccount
  name: boiarnikov-a-hw5-sa
  namespace: boiarnikov-a-hw5
roleRef:
  kind: Role
  name: pod-master
  apiGroup: rbac.authorization.k8s.io
