apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
  namespace: boiarnikov-a-hw6
spec:
  secretName: tls-cert-le
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: boiarnikov-a-hw6.mfti.devops-teta.ru
  dnsNames:
  - boiarnikov-a-hw6.mfti.devops-teta.ru
