apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: boiarnikov-a-hw6
data:
  default.conf: |-
    server {
      listen 80 default_server;
      root /var/www/html;
      server_name my-awesome-nginx-app;

      location /who {
        default_type text/plain;
        add_header Content-Type text/plain;
        return 200 'cool guy';
      }
    }

