services:
  backend:
    build: ./counter-backend
    environment:
      PORT: ${BACKEND_PORT}

  frontend:
    build: ./counter-frontend
    environment:
      PORT: ${FRONTEND_PORT}

  nginx:
    build: ./nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      DOMAIN: ${DOMAIN}
      FRONTEND_PORT: ${FRONTEND_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - ${PORT}:80
