---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-nfs-pvc
  namespace: boiarnikov-a-hw4
spec:
  storageClassName: postgres-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
