apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-nfs-csi
  namespace: boiarnikov-a-hw4
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.2.0.21
  share: /opt/nfs_share
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
