---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
spec:
  commonName: dev.boiarnikov-a-hw7.mfti.devops-teta.ru
  dnsNames:
    - dev.boiarnikov-a-hw7.mfti.devops-teta.ru
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
    - hosts:
        - dev.boiarnikov-a-hw7.mfti.devops-teta.ru
      secretName: tls-cert-le
  rules:
    - host: dev.boiarnikov-a-hw7.mfti.devops-teta.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
