apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boiarnikov-a-hw7
resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
  - ingress.yaml
  - cert.yaml
configMapGenerator:
  - name: nginx-config
    files:
      - config/default.conf
