apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: nginx-config
    behavior: replace
    files:
      - config/default.conf
patches:
  - path: increase-replicas-patch.yaml
